services:
  db:
    image: postgres:16-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data